### ISSUE TITLE
Applications not visible for users added later to the account

### ISSUE THREAD

**Issue by ameyasubhedar** [perpetualintelligence/pidotapp-bugs#2]
If we add more users to the account the permissions for the new users are not correctly updated and new users are not able to access application even if the Role is correctly updated.

**Comment by perpetualintelligence** [comment]
Thanks for reporting the issue, we found the root cause of the issue. The code was updating the permissions for the current logged in user. It needs to also update the permissions for all the users in the business account.

This change needs to tested thoroughly to avoid any regression.

In the mean time, the workaround is to use Refresh Sign In in the top right drop down in the main page 

![image](https://user-images.githubusercontent.com/62374075/77221960-040d9500-6b0c-11ea-9959-843dc01e9ffb.png)

**Comment by perpetualintelligence** [comment]
We have enhanced the Team management page and now your account administrator can refresh the permissions for your users directly from Team page.

![image](https://user-images.githubusercontent.com/62374075/82522043-193b7b80-9add-11ea-9402-713e93461d3b.png)
