### ISSUE TITLE
Translation Units does not translate automatically if I add new target languages.

### ISSUE THREAD

**Issue by VedantSahadeo** [perpetualintelligence/pidotapp-bugs#32]
I have created a translation page with three languages, which are translated correctly. But when I edit the Multilanguage page by adding new translation languages (for example : 2 new languages) , the (2) newly added languages won't get translated.
Like this.
![image](https://user-images.githubusercontent.com/62402148/81529948-be539880-9314-11ea-891b-add7d3722600.png)

I need to save the text again , In order to get the translation of the newly added languages.
![image](https://user-images.githubusercontent.com/62402148/81530292-6b2e1580-9315-11ea-88a0-8cb668c23b5a.png)

**Comment by perpetualintelligence** [comment]
@VedantSahadeo this behavior is by design. If you add new target languages to your translation page the existing translation unit in that page will not change automatically. The reason is the exiting translation unit may be approved or in production use, so we let user decide when to update the translations for the newly added target languages.
